// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsNt03LW1XchQkbsmcKeqVZkUeRDyYVqY',
    appId: '1:461694526804:web:35138f49aafffd6ba8d4c1',
    messagingSenderId: '461694526804',
    projectId: 'chirp-e5bed',
    authDomain: 'chirp-e5bed.firebaseapp.com',
    storageBucket: 'chirp-e5bed.appspot.com',
    measurementId: 'G-1Y4NJGHHSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNDBDrKHsDAQ54AVkWOV20RDyGhIHgGKc',
    appId: '1:461694526804:android:e4c3ac581d168f7ea8d4c1',
    messagingSenderId: '461694526804',
    projectId: 'chirp-e5bed',
    storageBucket: 'chirp-e5bed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ABpFjcHxZhOIDOuzniLygAjhu-462h8',
    appId: '1:461694526804:ios:6b4f2244ade2771aa8d4c1',
    messagingSenderId: '461694526804',
    projectId: 'chirp-e5bed',
    storageBucket: 'chirp-e5bed.appspot.com',
    iosClientId: '461694526804-p0m084lgeirf9g84gpqaiq6sguj3knc3.apps.googleusercontent.com',
    iosBundleId: 'in.sandeepkumar.chirrp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_ABpFjcHxZhOIDOuzniLygAjhu-462h8',
    appId: '1:461694526804:ios:6b4f2244ade2771aa8d4c1',
    messagingSenderId: '461694526804',
    projectId: 'chirp-e5bed',
    storageBucket: 'chirp-e5bed.appspot.com',
    iosClientId: '461694526804-p0m084lgeirf9g84gpqaiq6sguj3knc3.apps.googleusercontent.com',
    iosBundleId: 'in.sandeepkumar.chirrp',
  );
}
